CREATE SCHEMA IF NOT EXISTS sdc_test;

CREATE TABLE IF NOT EXISTS sdc_test.ex_crawl_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    website_name VARCHAR(255),
    base_url VARCHAR(255),
    crawl_log TEXT,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sdc_test.ex_crawl_log IS '采集数据同步日志表';
COMMENT ON COLUMN sdc_test.ex_crawl_log.website_name IS '网站名称';
COMMENT ON COLUMN sdc_test.ex_crawl_log.base_url IS '网站base_url';
COMMENT ON COLUMN sdc_test.ex_crawl_log.crawl_log IS '网站日志';
COMMENT ON COLUMN sdc_test.ex_crawl_log.update_time IS '日志更新时间';

CREATE TABLE IF NOT EXISTS sdc_test.ex_crawl_log_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    website_name VARCHAR(255),
    base_url VARCHAR(255),
    crawl_detail_log TEXT,
    update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sdc_test.ex_crawl_log_detail IS '采集数据日志表-详细日志';
COMMENT ON COLUMN sdc_test.ex_crawl_log_detail.website_name IS '网站名称';
COMMENT ON COLUMN sdc_test.ex_crawl_log_detail.base_url IS '网站base_url';
COMMENT ON COLUMN sdc_test.ex_crawl_log_detail.crawl_detail_log IS '网站详细日志';
COMMENT ON COLUMN sdc_test.ex_crawl_log_detail.update_time IS '日志更新时间';

CREATE INDEX IF NOT EXISTS idx_ex_crawl_log_website_name ON sdc_test.ex_crawl_log (website_name);
CREATE INDEX IF NOT EXISTS idx_ex_crawl_log_base_url ON sdc_test.ex_crawl_log (base_url);
CREATE INDEX IF NOT EXISTS idx_ex_crawl_log_detail_website_name ON sdc_test.ex_crawl_log_detail (website_name);
CREATE INDEX IF NOT EXISTS idx_ex_crawl_log_detail_base_url ON sdc_test.ex_crawl_log_detail (base_url);

CREATE OR REPLACE FUNCTION sdc_test.update_log_table_update_time()
RETURNS TRIGGER AS $$
BEGIN
    NEW.update_time = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ex_crawl_log_update_time ON sdc_test.ex_crawl_log;

CREATE TRIGGER trg_ex_crawl_log_update_time
BEFORE UPDATE ON sdc_test.ex_crawl_log
FOR EACH ROW
EXECUTE FUNCTION sdc_test.update_log_table_update_time();

DROP TRIGGER IF EXISTS trg_ex_crawl_log_detail_update_time ON sdc_test.ex_crawl_log_detail;

CREATE TRIGGER trg_ex_crawl_log_detail_update_time
BEFORE UPDATE ON sdc_test.ex_crawl_log_detail
FOR EACH ROW
EXECUTE FUNCTION sdc_test.update_log_table_update_time();